import React from "react";

const Head = () => {
  return (
    <>
      <title>Book IT || E-commerce</title>
      <meta content="widht=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated By Create Next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
